### ISSUE TITLE
Fix docs for raw deployment

### ISSUE THREAD

**Issue by rachitchauhan43** [kserve/website#297]
## Expected Behavior

Docs say to install `IngressClass`:
```
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
```
It errors out as `apiVersion: networking.k8s.io/v1beta1` is no longer supported by istio version mentioned in quick_hack script.

## Actual Behavior

Update apiVersion  `networking.k8s.io/v1`

## Steps to Reproduce the Problem

Try running quick_install.sh script with -r flag

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, OnPrem, etc.):
 - KServe Version: 0.11.1
