### ISSUE TITLE
Inference Graph YAML unformatted

### ISSUE THREAD

**Issue by yolk-pie-L** [kserve/website#352]
## Expected Behavior

When I was learning how to use InferenceGraph, I noticed that the API documentation YAML does not have proper indentation. 

You can check it at https://kserve.github.io/website/0.11/reference/api/#serving.kserve.io/v1alpha1.InferenceRouter

## Actual Behavior

The entire YAML file lacks any indentation, with all code being indented to the left.

## Additional Info
**Additional context**

**Comment by spolti** [comment]
Very nice finding @yolk-pie-L, if you want to contribute by fixing it, feel free, it will be really appreciated :)

**Comment by spolti** [comment]
@yuzisun @ckadner @terrytangyuan Hey guys, I was investigating this issue and found that:

These yaml files are loaded from: https://github.com/kserve/kserve/blob/master/pkg/apis/serving/v1alpha1/inference_graph.go#L104

and [this](https://github.com/kserve/website/blob/main/docs/hack/gen-api-reference-docs.sh) script will generate the reference api doc.

The script above uses [this tool](https://github.com/ahmetb/gen-crd-api-reference-doc)  to read all the api files and build this [api.md](https://github.com/kserve/website/blob/main/docs/reference/api.md)


However, the tool that reads the comments from the go files seems to be removing all the spaces from the yaml chunks.

On the other hand, if we try to add think like tabulations, (simple pressing tab) go fmt would remove that from the comments.

With that said, the only way I found to make the indentation to work with the current approach, is a little bit hacky, but solves the issue we have by updating these contents from go comments by adding tabulation controller chaaracter.
The proposed solution looks like:

1 - add tabulation character in the go comments, like (kserve/kserve side):
```yaml
// ```yaml
//
// kind: InferenceGraph
// metadata:
//
// \tname: canary-route
//
// spec:
//
// \tnodes:
//
//\t\troot:
//\t\t\trouterType: Splitter
...
```

2- And in the kserve/website, have a script to read these comments and apply the tabulation, e.g.:
```bash
...
        indented_line=""
        while [[ $next_line != "</code></pre>" ]]; do
            # Add break lines
            indented_line+="$next_line\n"
            # Read the next line
            read -r next_line
        done
        # Print the indented YAML content by applying the tabs
        tabs 2
        echo -e $indented_line
...
```

3 - call this script inside the `gen-api-reference-docs.sh` to properly format it, it will output in the `docs/reference/api.md` something like this:
```yaml
<p>InferenceRouter defines the router for each InferenceGraph node with one or multiple steps</p>
<pre><code class="language-yaml">
kind: InferenceGraph                                                                                                                                                                                                  
metadata:
  name: canary-route
spec:
  nodes:
    root:
      routerType: Splitter
...
```


Please let me know what you think about it, this approach is basically done in my end, I can send the PR for a better review.
