### ISSUE TITLE
Docs about using nodeSelector

### ISSUE THREAD

**Issue by jw-websensa** [kserve/website#39]
/kind feature

I am wondering if it is possible to set `nodeSelector` option for Tensorflow serving (or any other serving different that custom). 
I found some information about this in some issues, but they were not very specific.
If it is possible, it would be great to include any example in docs.

**Comment by markwinter** [comment]
You can use `nodeSelector` with `InferenceService` if you enable the feature flag in the Knative `config-features` configmap.

https://knative.dev/docs/admin/serving/feature-flags/#kubernetes-node-selector

```YAML
spec:
  predictor:
    nodeSelector:
      key: value
    tensorflow:
```
