### ISSUE TITLE
problem with gateway-api config, infrastructur's format incorrect

### ISSUE THREAD

**Issue by asdfsx** [kserve/website#468]
the gateway api config as below
https://github.com/kserve/website/blob/33341795c108aa4b27a64114c3fb0712010d89b8/docs/admin/gatewayapi_migration.md?plain=1#L76-L78

the infrastructure should be

```yaml
...
    infrastructure:
      labels:
        serving.kserve.io/gateway: kserve-ingress-gateway
```
